name: Deploy

on: push

jobs:
    first_job:
        runs-on: ubuntu-latest

        steps:
            - name: Print variable
              run: echo "${{ secrets.TOKEN_SECRET }}"

            - uses: actions/checkout@main        # replace @main with desired version
            - uses: fleshgrinder/setup-java@main # replace @main with desired version
            - run: java -version
