name: "Deploy Example"

on:
  push:
    branches: ["main"]

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    env:
      NAME: Jonhouseman
    
    strategy:
      matrix:
        message: ["DEV", "QA"]
    steps:
      - name: Pull
        run: echo "Hacemos pull del código $NAME"
      - name: Push
        run: echo "Hacemos push del código $NAME"
      - name: Actions
        run: echo "ejecutando actions $NAME"
      - name: Deploy
        run: echo "Deployamos en DEV $NAME"
      - name: Steps terminados con éxito
        run: echo "${{ matrix.message }}"
  deploy-production:
    needs: deploy-test
    runs-on: ubuntu-latest
    env:
      NAME: Jonhouseman
    steps:
      - name: Root
        run: ls -al
      - name: Action
        uses: actions/checkout@v4
      - name: RootDirectory
        run: ls -al
      - name: RootDirectory  
        run: echo "Hacemos pull to master $NAME"
      - run: echo "Hacemos push to master"
      - run: echo "ejecutando actions to master"
      - run: echo "Deployamos to master"
