name: "Deploy Example"

on:
  push:
    branches: ["main"]

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hacemos pull del código"
      - run: echo "Hacemos push del código"
      - run: echo "ejecutando actions"
      - run: echo "Deployamos en DEV"
  deploy-production:
    needs: deploy-test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hacemos pull to master"
      - run: echo "Hacemos push to master"
      - run: echo "ejecutando actions to master"
      - run: echo "Deployamos to master"
