name: "Deploy Example"

on:
  push:
    branches: ["main"]

jobs:
  deploy-examen:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hacemos pull del código"
      - run: echo "Hacemos push del código"
      - run: mvn compile
      - run: echo "Deployamos"
