name: "Deploy Example"

on:
  push:
    branches: ["main"]

jobs:
  deploy-test:
    runs-on: ubuntu-latest
    env:
      NAME: Jonhouseman
    steps:
      - name: Pull
        run: echo "Hacemos pull del código $NAME"
      - name: Push
        run: echo "Hacemos push del código $NAME"
      - name: Actions
        run: echo "ejecutando actions $NAME"
      - name: Deploy
        run: echo "Deployamos en DEV $NAME"
  deploy-production:
    needs: deploy-test
    runs-on: ubuntu-latest
    steps:
      - run: echo "Hacemos pull to master"
      - run: echo "Hacemos push to master"
      - run: echo "ejecutando actions to master"
      - run: echo "Deployamos to master"
